curso:
  nombre: "Ennuob"
  timezone: "America/Santiago"

calendario:
  periodo:
    fecha_inicio: "2026-03-16"
    numero_semanas: 19

  secciones:
    "Sección 1": # Juan Carlos
      teorica:   { dia_semana: "Tuesday", inicio: "8:30", fin: "10:00" }
      seminario: { dia_semana: "Wednesday", inicio: "12:00", fin: "13:30" }

    "Sección 2": # Alexander Riquelme
      teorica:   { dia_semana: "Tuesday", inicio: "16:45", fin: "18:15" }
      seminario: { dia_semana: "Friday", inicio: "12:00", fin: "13:30" }

    "Sección 3": # Ingrid Galaz
      teorica:   { dia_semana: "Tuesday", inicio: "10:15", fin: "11:45" }
      seminario: { dia_semana: "Friday", inicio: "15:00", fin: "16:30" }

    "Sección 4": # Caroll Cuellar
      teorica:   { dia_semana: "Tuesday", inicio: "10:15", fin: "11:45" }
      seminario: { dia_semana: "Friday", inicio: "16:45", fin: "18:15" }

  profesores_base:
    - { seccion: "Sección 1", actividad: "Clase teórica", profesores: "JCS" }
    - { seccion: "Sección 1", actividad: "Seminario", profesores: ["JM", "MB", "VB"] }

    - { seccion: "Sección 2", actividad: "Clase teórica", profesores: "AR" }
    - { seccion: "Sección 2", actividad: "Seminario", profesores: ["NV", "RM", "SM"] }

    - { seccion: "Sección 3", actividad: "Clase teórica", profesores: "IG" }
    - { seccion: "Sección 3", actividad: "Seminario", profesores: ["MB", "GM", "DH"] }

    - { seccion: "Sección 4", actividad: "Clase teórica", profesores: "CC" }
    - { seccion: "Sección 4", actividad: "Seminario", profesores: ["DH", "GM", "VB"] }

  temas_teoricos:
    1: "Lógica 1"
    2: "Lógica 2"
    3: "Lógica 3 teórico-práctico" # perdemos 1 seminario
    4: "Modelos y Derivadas 1 teórico-práctico" # perdemos 1 seminario
    5: "Modelos y Derivadas 2"
    6: "Modelos y Derivadas 3"
    7: "Certamen 1" # perdemos 1 seminario
    8: "Modelos y Derivadas 4"
    9: "Actividad Autónoma Portafolio"
    10: "Semana Receso"
    11: "Modelos y Derivadas 5"
    12: "Linealización de modelos"
    13: "Trigonometría y Vectores 1"
    14: "Trigonometría y Vectores 2"
    15: "Trigonometría y Vectores 3"
    16: "Certamen 2"
    17: "Trabajo Autónomo"
    18: "Examen Primera Oportunidad"
    19: "Examen Segunda Oportunidad"

# tablas de frecuancia o estadoisticas
# tipos de varaibles

  temas_seminarios:
    1: "Lógica 1"
    2: "Lógica 2"
    3: "Sin Seminario" # perdemos 1 seminario
    4: "Sin Seminario (semana mechona)" # perdemos 1 seminario
    5: "Modelos y Derivadas 2"
    6: "Modelos y Derivadas 3"
    7: "Sin Seminario" # perdemos 1 seminario
    8: "Revisión Certamen 1"
    9: "Modelos y Derivadas 4"
    10: "Semana Receso"
    11: "Modelos y Derivadas 5"
    12: "Linealización de modelos"
    13: "Trigonometría y Vectores 1"
    14: "Trigonometría y Vectores 2"
    15: "Trigonometría y Vectores 3"
    16: "Revisión Certamen 2"
    17: "Trabajo Autónomo"
    18: "Examen Primera Oportunidad"
    19: "Examen Segunda Oportunidad"

  excepciones_tema:
    - { seccion: "Sección 2", semana: 4, actividad: "Clase teórica", tema: "Sin Clase (semana mechona)" }
    - { seccion: "Sección 2", semana: 4, actividad: "Seminario", tema: "Modelos y Derivadas 1 teórico-práctico" }

# taller 1 después de terminar lógica
# retroalimentación certamen 1 desface 1 semana y hay que adelantar en la semana de repaso
# semana mechona alexander debe tomar viernes el teórico (seccion 2)
# taller 2 en modelos y derivadas 4
# taller 3 en trigonometria 2


# Unidad 1 una entrega
# Unidad 2 2 entregas
# Unidad 3 1 entrega
# Esquema
# Rúbrica del año pasado
# Carta para recomendar
# Cosas iniciales (cuestionario inicial)
# Cosas finales (reflexiones finales)
# checklist de avances


  evaluaciones:
    - { modo: "por_filtro", seccion: "Sección 1", semana: 2, actividad: "Seminario", tipo: "Taller", observaciones: "Taller Unidad 1" }
    - { modo: "por_filtro", seccion: "Sección 1", semana: 9, actividad: "Seminario", tipo: "Taller", observaciones: "Taller Unidad 2" }
    - { modo: "por_filtro", seccion: "Sección 1", semana: 14, actividad: "Seminario", tipo: "Taller", observaciones: "Taller Unidad 3" }
    - { modo: "por_filtro", seccion: "Sección 1", semana: 7, actividad: "Clase teórica", tipo: "Certamen", observaciones: "Certamen 1" }
    - { modo: "por_filtro", seccion: "Sección 1", semana: 16, actividad: "Clase teórica", tipo: "Certamen", observaciones: "Certamen 2" }
    - { modo: "por_filtro", seccion: "Sección 1", semana: 12, actividad: "Seminario", tipo: "Trabajo práctico", observaciones: "Trabajo Práctico" }
    - { modo: "por_filtro", seccion: "Sección 1", semana: 18, actividad: "Clase teórica", tipo: "Examen", observaciones: "Examen 1" }
    - { modo: "por_filtro", seccion: "Sección 1", semana: 19, actividad: "Clase teórica", tipo: "Examen", observaciones: "Examen 2" }

    - { modo: "por_filtro", seccion: "Sección 2", semana: 2, actividad: "Seminario", tipo: "Taller", observaciones: "Taller Unidad 1" }
    - { modo: "por_filtro", seccion: "Sección 2", semana: 9, actividad: "Seminario", tipo: "Taller", observaciones: "Taller Unidad 2" }
    - { modo: "por_filtro", seccion: "Sección 2", semana: 14, actividad: "Seminario", tipo: "Taller", observaciones: "Taller Unidad 3" }
    - { modo: "por_filtro", seccion: "Sección 2", semana: 7, actividad: "Clase teórica", tipo: "Certamen", observaciones: "Certamen 1" }
    - { modo: "por_filtro", seccion: "Sección 2", semana: 16, actividad: "Clase teórica", tipo: "Certamen", observaciones: "Certamen 2" }
    - { modo: "por_filtro", seccion: "Sección 2", semana: 12, actividad: "Seminario", tipo: "Trabajo práctico", observaciones: "Trabajo Práctico" }
    - { modo: "por_filtro", seccion: "Sección 2", semana: 18, actividad: "Clase teórica", tipo: "Examen", observaciones: "Examen 1" }
    - { modo: "por_filtro", seccion: "Sección 2", semana: 19, actividad: "Clase teórica", tipo: "Examen", observaciones: "Examen 2" }

    - { modo: "por_filtro", seccion: "Sección 3", semana: 2, actividad: "Seminario", tipo: "Taller", observaciones: "Taller Unidad 1" }
    - { modo: "por_filtro", seccion: "Sección 3", semana: 9, actividad: "Seminario", tipo: "Taller", observaciones: "Taller Unidad 2" }
    - { modo: "por_filtro", seccion: "Sección 3", semana: 14, actividad: "Seminario", tipo: "Taller", observaciones: "Taller Unidad 3" }
    - { modo: "por_filtro", seccion: "Sección 3", semana: 7, actividad: "Clase teórica", tipo: "Certamen", observaciones: "Certamen 1" }
    - { modo: "por_filtro", seccion: "Sección 3", semana: 16, actividad: "Clase teórica", tipo: "Certamen", observaciones: "Certamen 2" }
    - { modo: "por_filtro", seccion: "Sección 3", semana: 12, actividad: "Seminario", tipo: "Trabajo práctico", observaciones: "Trabajo Práctico" }
    - { modo: "por_filtro", seccion: "Sección 3", semana: 18, actividad: "Clase teórica", tipo: "Examen", observaciones: "Examen 1" }
    - { modo: "por_filtro", seccion: "Sección 3", semana: 19, actividad: "Clase teórica", tipo: "Examen", observaciones: "Examen 2" }

    - { modo: "por_filtro", seccion: "Sección 4", semana: 2, actividad: "Seminario", tipo: "Taller", observaciones: "Taller Unidad 1" }
    - { modo: "por_filtro", seccion: "Sección 4", semana: 9, actividad: "Seminario", tipo: "Taller", observaciones: "Taller Unidad 2" }
    - { modo: "por_filtro", seccion: "Sección 4", semana: 14, actividad: "Seminario", tipo: "Taller", observaciones: "Taller Unidad 3" }
    - { modo: "por_filtro", seccion: "Sección 4", semana: 7, actividad: "Clase teórica", tipo: "Certamen", observaciones: "Certamen 1" }
    - { modo: "por_filtro", seccion: "Sección 4", semana: 16, actividad: "Clase teórica", tipo: "Certamen", observaciones: "Certamen 2" }
    - { modo: "por_filtro", seccion: "Sección 4", semana: 12, actividad: "Seminario", tipo: "Trabajo práctico", observaciones: "Trabajo Práctico" }
    - { modo: "por_filtro", seccion: "Sección 4", semana: 18, actividad: "Clase teórica", tipo: "Examen", observaciones: "Examen 1" }
    - { modo: "por_filtro", seccion: "Sección 4", semana: 19, actividad: "Clase teórica", tipo: "Examen", observaciones: "Examen 2" }

    - { modo: "por_filtro", seccion: "Sección 1", semana: 17, actividad: "Seminario", tipo: "Portafolio", observaciones: "Portafolio" }
    - { modo: "por_filtro", seccion: "Sección 2", semana: 17, actividad: "Seminario", tipo: "Portafolio", observaciones: "Portafolio" }
    - { modo: "por_filtro", seccion: "Sección 3", semana: 17, actividad: "Seminario", tipo: "Portafolio", observaciones: "Portafolio" }
    - { modo: "por_filtro", seccion: "Sección 4", semana: 17, actividad: "Seminario", tipo: "Portafolio", observaciones: "Portafolio" }

  pausas_academicas: []
  semanas_trabajo_autonomo: [17]

  bloques:
    definicion:
      "3": { inicio: "12:00", fin: "13:30" }
      "4": { inicio: "15:00", fin: "16:30" }
    protegidos:
      - { fecha: "2026-04-01", bloque: "3" }
      - { fecha: "2026-05-04", bloque: "4" }
      - { fecha: "2026-06-11", bloque: "3" }
      - { fecha: "2026-06-23", bloque: "4" }

  feriados:
    usar_automaticos_chile: true
    manuales: []



misiones:
  alias_seccion:
    "Sección 1": "Sección 1 (Miércoles)"

  coordinacion:
    pec_por_seccion:
      "Sección 1": "JCS"
      "Sección 2": "AR"
      "Sección 3": "IG"
      "Sección 4": "CC"
    pcc_por_seccion:
      "Sección 1": "TY"
      "Sección 2": "TY"
      "Sección 3": "TY"
      "Sección 4": "TY"

  # overrides SOLO si quieres romper el ciclo normal
  overrides_responsables:
    # - { tipo_evento: "Control", seccion: "Sección 1", fecha_evento: "2026-03-26", slot: "C" }
    # - { tipo_evento: "Control", seccion: "Sección 1", fecha_evento: "2026-04-02", responsables: ["GM"] }
    - { tipo_evento: "Taller", seccion: "Sección 1", fecha_evento: "2026-03-25", paso: "construir_taller", responsables: ["IG"] }
    - { tipo_evento: "Taller", seccion: "Sección 2", fecha_evento: "2026-03-27", paso: "construir_taller", responsables: ["IG"] }
    - { tipo_evento: "Taller", seccion: "Sección 3", fecha_evento: "2026-03-27", paso: "construir_taller", responsables: ["IG"] }
    - { tipo_evento: "Taller", seccion: "Sección 4", fecha_evento: "2026-03-27", paso: "construir_taller", responsables: ["IG"] }
    - { tipo_evento: "Taller", seccion: "Sección 2", fecha_evento: "2026-03-27", paso: "corregir_taller", responsables: ["RM"] }
    - { tipo_evento: "Taller", seccion: "Sección 1", fecha_evento: "2026-03-25", paso: "corregir_taller", responsables: ["VB"] }

  protocolos:
    Control:
      construir_control:
        detalle: "Construcción del control."
        offset_dias: -7
      escanear:
        detalle: "Escanear control y subir a carpeta."
        offset_dias: 7
      corregir_y_notas:
        detalle: "Corregir control y subir notas."
        offset_dias: 7

    Certamen:
      pedir_preguntas:
        detalle: "Enviar preguntas para certamen con solución."
        offset_dias: -14
      construir_control:
        detalle: "Construcción del certamen."
        offset_dias: -7
      pauta_prueba:
        detalle: "Pauta del certamen."
        offset_dias: -4
      corregir_y_notas:
        detalle: "Corregir certamen y subir notas."
        offset_dias: 7

    Trabajo práctico:
      revisar_tp:
        detalle: "Revisar TP y subir nota."
        offset_dias: 7

    Examen:
      pedir_preguntas:
        detalle: "Preguntas para examen con solución."
        offset_dias: -14
      construir_examen:
        detalle: "Construcción del examen."
        offset_dias: -7
      pauta_examen:
        detalle: "Pauta del examen."
        offset_dias: -4
      corregir_examen:
        detalle: "Corregir examen."
        offset_dias: 7

    Taller:
      construir_taller:
        responsables: "Asignar"
        detalle: "Construcción del taller colaborativo con versiones A, B, C y D."
        offset_dias: -7
      corregir_taller:
        responsables: "Asignar"
        detalle: "Corrección del taller según la versión asignada."
        offset_dias: 7

    Laboratorio:
      preparar_material_previo:
        responsables: "PEC"
        detalle: "Preparar material previo / resumen para el laboratorio."
        offset_dias: -5
      grabar_video_solucion:
        responsables: "Asignar"
        detalle: "Grabar video de la solución del laboratorio."
        offset_dias: 2
      corregir_informe_laboratorio:
        responsables: "Todos"
        detalle: "Corregir informe de laboratorio."
        offset_dias: 7

emails:
  from_name: "J. Tomás Yáñez"
  cc: []
  estado_envios_path: "data/email_log.json"

  resumen_semanal:
    dia_envio: "Friday"
    hora_envio: "09:00"
    asunto: "[{curso}] Resumen semanal {fecha_inicio_semana}–{fecha_fin_semana}"
    cuerpo: |
      Buen día {nombre_prof},

      Este es tu resumen para la semana del {fecha_inicio_semana} al {fecha_fin_semana} en el curso {curso}.

      ====================
      MISIONES
      ====================

      {lista_misiones}

      ====================
      CLASES DE LA SEMANA
      ====================

      {lista_clases}

      Si no aparece ninguna misión, eso significa que no tienes misiones planificadas originalmente para esta semana.
      De todos modos, puede haber coordinaciones adicionales conversadas con el equipo docente que no estén reflejadas aquí.

      Puedes revisar el calendario completo aquí:
      https://calendario-curso.streamlit.app

      Saludos,
      {from_name}


# misiones:
#   aleatoriedad:
#     semilla: 42

#   secciones:
#     - "Sección 1"
#     - "Sección 2"
#     - "Sección 3"
#     - "Sección 4"

#   # alias_seccion:
#   #   "Sección 1": "Sección 1 (JCS)"
#   #   "Sección 2": "Sección 2 (AR)"
#   #   "Sección 3": "Sección 3 (IG)"
#   #   "Sección 4": "Sección 4 (CC)"

#   profesores:
#     - { codigo: "AR", horas_contrato: 10 }
#     - { codigo: "JCS", horas_contrato: 10 }
#     - { codigo: "GM", horas_contrato: 10 }
#     - { codigo: "VB", horas_contrato: 10 }
#     - { codigo: "NV", horas_contrato: 10 }
#     - { codigo: "CC", horas_contrato: 10 }
#     - { codigo: "IG", horas_contrato: 10 }
#     - { codigo: "TY", horas_contrato: 10 }
#     - { codigo: "JM", horas_contrato: 10 }
#     - { codigo: "EG", horas_contrato: 10 }
#     - { codigo: "RL", horas_contrato: 10 }
#     - { codigo: "DH", horas_contrato: 10 }
#     - { codigo: "SM", horas_contrato: 10 }

# # en medi se asigna a quien se asigna crear un control y pauta.   
# # cada control va por sección, no por curso, forma A y forma B
# # subir guia de seminario entre todos los profes, eso verlo entre los profes, tal vez verlo en general
# # tal vez hacer una pool de todos los profes, incluyendo las veces que se repiten, y de ahí ir tomando las misiones
# # pedir misiones a la gente antigua primero
# # corrección todos participan y cuanto depende de su carga horaria (eso lo ve caroll, no preocuparse)

#   protocolos:
#     Control:
#       construir_control:
#         responsables: "Asignar"
#         detalle: "Construcción del control."
#         offset_dias: -7
#       pauta_prueba:
#         responsables: "Asignar"
#         detalle: "Pauta del control."
#         offset_dias: -7
#       escanear:
#         responsables: "Asignar"
#         detalle: "Escanear control y subir a carpeta."
#         offset_dias: 7
#       corregir_y_notas:
#         responsables: "Asignar"
#         detalle: "Corregir control y subir notas."
#         offset_dias: 7

#     Certamen:
#       pedir_preguntas:
#         responsables: "Todos"
#         detalle: "Cada profesor propone preguntas para el certamen."
#         offset_dias: -14
#       construir_control:
#         responsables: "Asignar"
#         detalle: "Construcción del certamen."
#         offset_dias: -7
#       pauta_prueba:
#         responsables: "Asignar"
#         detalle: "Pauta del certamen."
#         offset_dias: -3
#       revisar_prueba:
#         responsables: "Asignar"
#         detalle: "Revisión final del certamen."
#         offset_dias: -3
#       escanear:
#         responsables: "Asignar"
#         detalle: "Escanear certamen y subir a carpeta."
#         offset_dias: 14
#       corregir_y_notas:
#         responsables: "Asignar"
#         detalle: "Corregir certamen y subir notas."
#         offset_dias: 14

#     Trabajo práctico:
#       revisar_tp:
#         responsables: "Todos"
#         detalle: "Revisar TP y subir nota."
#         offset_dias: 14

#     Examen:
#       pedir_preguntas:
#         responsables: "Todos"
#         detalle: "Preguntas para examen."
#         offset_dias: -21
#       construir_examen:
#         responsables: "Asignar"
#         detalle: "Construcción del examen."
#         offset_dias: -14
#       pauta_examen:
#         responsables: "Asignar"
#         detalle: "Pauta del examen."
#         offset_dias: -7
#       corregir_examen:
#         responsables: "Asignar"
#         detalle: "Corregir examen."
#         offset_dias: 14

#   reglas_asignacion:
#     horas:
#       Clase teórica: 1.5
#       Seminario: 1.5
#       Laboratorio: 0.75

#     dividir_horas_entre_profesores_del_mismo_bloque: false

#     alcance_por_tipo_mision:
#       construir_control: "sección"
#       pauta_prueba: "sección"
#       revisar_prueba: "sección"
#       construir_examen: "sección"
#       pauta_examen: "sección"
#       corregir_examen: "sección"
#       escanear: "seccion"
#       corregir_y_notas: "seccion"
#       revisar_tp: "seccion"

#     estrategia:
#       tipo: "menor_carga_ajustada"
#       peso_misiones_previas: 1.0

# emails:
#   pec_por_seccion:
#     "Sección 1": "TY"
#     "Sección 2": "IG"

#   from_name: "J. Tomás Yáñez"

#   cc: []

#   estado_envios_path: "data/email_log.json"

# resumen_semanal:
#   dia_envio: "Friday"
#   hora_envio: "09:00"
#   asunto: "[{curso}] Resumen semanal {fecha_inicio_semana}–{fecha_fin_semana}"
#   cuerpo: |
#     Buen día {nombre_prof},

#     Este es tu resumen para la semana del {fecha_inicio_semana} al {fecha_fin_semana} en el curso {curso}.

#     ====================
#     MISIONES
#     ====================

#     {lista_misiones}

#     ====================
#     CLASES DE LA SEMANA
#     ====================

#     {lista_clases}

#     Si no aparece ninguna misión, eso significa que no tienes tareas planificadas originalmente para esta semana.
#     De todos modos, puede haber coordinaciones adicionales conversadas con los PEC o con el equipo docente que no estén reflejadas aquí.

#     Puedes revisar el calendario completo aquí:
#     https://calendario-curso.streamlit.app

#     Saludos,
#     {from_name}
